# Site settings
title: Recipe Blog
header-img: img/home-bg.jpg
email: adamzr@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/recipe-blog"
url: "http://adamzr.github.io"
twitter_username: adamzr
github_username:  adamzr
facebook_username:  azrich

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
